### ISSUE TITLE
Feature request idea: automatic retry upon error

### ISSUE THREAD

**Issue by EvoDyn** [shloop/google-book-scraper#5]
Seeing errors in the log that state "Scraper error: error sending request for url <url>" and the download stops after that point for the magazine issue. Restarting the download fixes the issue (suspect that rate limiting could fix this). An idea would be to do a retry or N retries of that issue after waiting a bit. Otherwise, loving the software!

**Comment by shloop** [comment]
Implemented in v0.3.4. Configurable with `-r`/`--download-attempts` command line parameter.
